### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [kikugie/compact-scoreboard#2]
if compatible could you mark 1.19.3 on modrinth?

**Comment by Aces-and-Jacks** [comment]
hmm. Archived so closing

**Comment by kikugie** [comment]
This mod was merged into https://modrinth.com/mod/techutils

**Comment by Aces-and-Jacks** [comment]
oh. Would you be able update that on the modrinth page incase others come by your mod? Only if you want to tho...
